spring.application.name=rh
server.address=0.0.0.0
server.port=9000

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/rh
spring.datasource.username=postgres
spring.datasource.password=supersecret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# BATCH
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# JWT
application.security.jwt.secret-key=2b36a335c2c192370d18247f821b843bd18bcf06da565dd4ddc94860bbd84ecc
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# SCHEDULERS
app.schedulers.free-operators-reset.enabled=true

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=baha140700m@gmail.com
spring.mail.password=mcsj esgd maus aukn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# LOGGING
logging.level.org.springframework.boot.context.config=DEBUG